In [1]:
%%script C:\Users\Jan Catherine\AppData\Local\Programs\Python\Python38\python.exe
import sys
print(sys.version)

3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]


In [2]:
pwd

'C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN'

In [3]:
import os
os.chdir('../../Data_Collection_02/02_Preprocessing/05_CNN')

In [4]:
import matplotlib.pyplot as plt
import os
import re
import shutil
import string
import tensorflow as tf
from tensorflow.keras import regularizers

from tensorflow.keras import layers
from tensorflow.keras import losses

from collections import Counter

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from tensorflow.keras import preprocessing
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.losses import BinaryCrossentropy


from sklearn.model_selection import KFold

#import pydot

In [5]:
dataset = pd.read_csv('02_All_Train.csv', encoding='latin-1')
testdata = pd.read_csv('02_All_Test.csv', encoding='latin-1')

train_data = dataset
test_data = testdata

test_data.dropna(axis = 0, how ='any',inplace=True) 

In [6]:
new_model1 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\Title')
new_model1.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4_1 (Embedding)   (None, 90, 64)            750016    
                                                                 
 conv1d_4_1 (Conv1D)         (None, 88, 128)           24704     
                                                                 
 global_max_pooling1d_4_1 (  (None, 128)               0         
 GlobalMaxPooling1D)                                             
                                                                 
 dropout_4_1 (Dropout)       (None, 128)               0         
                                                                 
 dense_4_1 (Dense)           (None, 2)                 258       
                                                                 
Total params: 774978 (2.96 MB)
Trainable params: 774978 (2.96 MB)
Non-trainable params: 0 (0.00 Byte)
__________________

In [7]:
import json
with open('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\Title\\Title.json') as json_file1:
    json_string1 = json.loads(json_file1.read())
tokenizer1 = tf.keras.preprocessing.text.tokenizer_from_json(json_string1)

In [8]:
new_model2 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\Desc')
new_model2.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 50, 64)            1280064   
                                                                 
 conv1d_4 (Conv1D)           (None, 48, 128)           24704     
                                                                 
 global_max_pooling1d_4 (Gl  (None, 128)               0         
 obalMaxPooling1D)                                               
                                                                 
 dropout_4 (Dropout)         (None, 128)               0         
                                                                 
 dense_4 (Dense)             (None, 2)                 258       
                                                                 
Total params: 1305026 (4.98 MB)
Trainable params: 1305026 (4.98 MB)
Non-trainable params: 0 (0.00 Byte)
________________

In [9]:
import json
with open('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\Desc\\Desc.json') as json_file2:
    json_string2 = json.loads(json_file2.read())
tokenizer2 = tf.keras.preprocessing.text.tokenizer_from_json(json_string2)

In [10]:
new_model3 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\URLchar')
new_model3.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 260, 64)           750016    
                                                                 
 conv1d_4 (Conv1D)           (None, 258, 128)          24704     
                                                                 
 global_max_pooling1d_4 (Gl  (None, 128)               0         
 obalMaxPooling1D)                                               
                                                                 
 dropout_4 (Dropout)         (None, 128)               0         
                                                                 
 dense_4 (Dense)             (None, 2)                 258       
                                                                 
Total params: 774978 (2.96 MB)
Trainable params: 774978 (2.96 MB)
Non-trainable params: 0 (0.00 Byte)
__________________

In [11]:
with open('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\URLchar\\URLchar.json') as json_file3:
    json_string3 = json.load(json_file3)
tokenizer3 = tf.keras.preprocessing.text.tokenizer_from_json(json_string3)

In [12]:
new_model4 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\URLword')
new_model4.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4_word (Embeddin  (None, 40, 64)            750016    
 g)                                                              
                                                                 
 conv1d_4_word (Conv1D)      (None, 38, 128)           24704     
                                                                 
 global_max_pooling1d_4_wor  (None, 128)               0         
 d (GlobalMaxPooling1D)                                          
                                                                 
 dropout_4_word (Dropout)    (None, 128)               0         
                                                                 
 dense_4_word (Dense)        (None, 2)                 258       
                                                                 
Total params: 774978 (2.96 MB)
Trainable params: 77497

In [13]:
with open('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\URLword\\URLword.json') as json_file4:
    json_string4 = json.load(json_file4)
tokenizer4 = tf.keras.preprocessing.text.tokenizer_from_json(json_string4)

In [14]:
new_model5 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\All_No_URL')
new_model5.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 input_2 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 average (Average)           (None, 2)                    0         ['input_1[0][0]',             
                                                                     'input_2[0][0]']             
                                                                                                  
Total params: 0 (0.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 0 (0.00 Byte

In [15]:
x_test1  = np.array( tokenizer1.texts_to_sequences(test_data['Title'].tolist()) )
x_test1 = pad_sequences(x_test1, padding='post', maxlen=90)


C:\Users\Jan Catherine\AppData\Local\Temp\ipykernel_13820\3328888694.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test1  = np.array( tokenizer1.texts_to_sequences(test_data['Title'].tolist()) )


In [16]:
x_test2  = np.array( tokenizer2.texts_to_sequences(test_data['Description'].tolist()) )
x_test2 = pad_sequences(x_test2, padding='post', maxlen=50)


C:\Users\Jan Catherine\AppData\Local\Temp\ipykernel_13820\4054164706.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test2  = np.array( tokenizer2.texts_to_sequences(test_data['Description'].tolist()) )


In [17]:
x_test3  = np.array( tokenizer3.texts_to_sequences(test_data['URL'].tolist()) )
x_test3 = pad_sequences(x_test3, padding='post', maxlen=260)


C:\Users\Jan Catherine\AppData\Local\Temp\ipykernel_13820\1739419470.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test3  = np.array( tokenizer3.texts_to_sequences(test_data['URL'].tolist()) )


In [18]:
x_test4  = np.array( tokenizer4.texts_to_sequences(test_data['URL'].tolist()) )
x_test4 = pad_sequences(x_test4, padding='post', maxlen=40)


C:\Users\Jan Catherine\AppData\Local\Temp\ipykernel_13820\2258211110.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test4  = np.array( tokenizer4.texts_to_sequences(test_data['URL'].tolist()) )


In [19]:
from keras. models import Model
from keras.layers import *

"""
merged_layers = concatenate([new_model1.output, new_model2.output, new_model3.output, new_model4.output])
x = BatchNormalization()(merged_layers)
x = Dense(300)(x)
x = PReLU()(x)
x = Dropout(0.2)(x)
x = Dense(1)(x)
x = BatchNormalization()(x)
out = Activation('sigmoid')(x)

merged_model = Model([new_model1.input(), new_model2.input(), new_model3.input(), new_model4.input()], [out])
merged_model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['CategoricalAccuracy'])
"""

"\nmerged_layers = concatenate([new_model1.output, new_model2.output, new_model3.output, new_model4.output])\nx = BatchNormalization()(merged_layers)\nx = Dense(300)(x)\nx = PReLU()(x)\nx = Dropout(0.2)(x)\nx = Dense(1)(x)\nx = BatchNormalization()(x)\nout = Activation('sigmoid')(x)\n\nmerged_model = Model([new_model1.input(), new_model2.input(), new_model3.input(), new_model4.input()], [out])\nmerged_model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['CategoricalAccuracy'])\n"

In [20]:
for layer in new_model1.layers:
    print(layer.get_output_at(0).get_shape().as_list())

[None, 90, 64]
[None, 88, 128]
[None, 128]
[None, 128]
[None, 2]


In [21]:
merged_model=tf.keras.layers.Average()([new_model1.output, new_model2.output, new_model3.output, new_model4.output])
#merged_model=BatchNormalization()(merged_model)
#merged_model=tf.keras.layers.Dense(128, activation='relu')(merged_model)
#merged_model=tf.keras.layers.Dropout(0.2)(merged_model)
#merged_model=tf.keras.layers.Dense(2,activation='relu')(merged_model)
#merged_model = BatchNormalization()(merged_model)

final_model = tf.keras.models.Model(inputs=[new_model1.output, new_model2.output, new_model3.output, new_model4.output], outputs=merged_model)
final_model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['CategoricalAccuracy'])

In [22]:
final_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 input_2 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 input_3 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 input_4 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                              

In [23]:
print("Generate predictions for all samples")
predictions1 = new_model1.predict(x_test1)
print(predictions1)
predict_results1 = predictions1.argmax(axis=1)

Generate predictions for all samples
51/51 [==============================] - 0s 4ms/step
[[0.9986129  0.00138709]
 [0.99433863 0.00566135]
 [0.99058545 0.00941452]
 ...
 [0.00372173 0.9962783 ]
 [0.9556978  0.04430221]
 [0.9832606  0.01673941]]


In [24]:
print("Generate predictions for all samples")
predictions2 = new_model2.predict(x_test2)
print(predictions2)
predict_results2 = predictions2.argmax(axis=1)

Generate predictions for all samples
51/51 [==============================] - 0s 3ms/step
[[0.98725384 0.01274614]
 [0.99856377 0.00143621]
 [0.9836872  0.01631275]
 ...
 [0.00634583 0.9936542 ]
 [0.9606546  0.03934541]
 [0.9776184  0.02238159]]


In [25]:
print("Generate predictions for all samples")
predictions3 = new_model3.predict(x_test3)
print(predictions3)
predict_results3 = predictions3.argmax(axis=1)

Generate predictions for all samples
51/51 [==============================] - 0s 7ms/step
[[0.99622256 0.00377741]
 [0.9815708  0.01842912]
 [0.7696982  0.23030218]
 ...
 [0.8019059  0.19809413]
 [0.9904026  0.00959739]
 [0.9476664  0.05233336]]


In [26]:
print("Generate predictions for all samples")
predictions4 = new_model4.predict(x_test4)
print(predictions4)
predict_results4 = predictions4.argmax(axis=1)

Generate predictions for all samples
51/51 [==============================] - 0s 3ms/step
[[0.9864073  0.01359272]
 [0.9703854  0.02961461]
 [0.92938405 0.07061591]
 ...
 [0.9523344  0.0476656 ]
 [0.9263759  0.07362404]
 [0.9869116  0.01308842]]


In [27]:
print("Generate predictions for all samples")
predictions5 = new_model5.predict([predictions1, predictions2])
print(predictions5)
predict_results5 = predictions5.argmax(axis=1)

Generate predictions for all samples
51/51 [==============================] - 0s 1ms/step
[[0.9929334  0.00706661]
 [0.9964512  0.00354878]
 [0.98713636 0.01286364]
 ...
 [0.00503378 0.99496627]
 [0.9581762  0.04182381]
 [0.9804395  0.0195605 ]]


In [28]:
print("Generate predictions for all samples")
predictions = final_model.predict([predictions1, predictions2, predictions3, predictions4 ])
print(predictions)
predict_results = predictions.argmax(axis=1)

Generate predictions for all samples
51/51 [==============================] - 0s 1ms/step
[[0.99212414 0.00787584]
 [0.98621464 0.01378532]
 [0.9183387  0.08166134]
 ...
 [0.44107696 0.55892307]
 [0.9582827  0.04171726]
 [0.97386426 0.0261357 ]]


In [29]:
test_data['pred_fake_title']= predict_results1
test_data['pred_fake_title'] = np.where((test_data.pred_fake_title == '0'),0,test_data.pred_fake_title)
test_data['pred_fake_title'] = np.where((test_data.pred_fake_title == '1'),1,test_data.pred_fake_title)

In [30]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_title'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1428
           1       0.76      0.71      0.73       184

    accuracy                           0.94      1612
   macro avg       0.86      0.84      0.85      1612
weighted avg       0.94      0.94      0.94      1612



In [31]:
test_data['pred_fake_desc']= predict_results2
test_data['pred_fake_desc'] = np.where((test_data.pred_fake_desc == '0'),0,test_data.pred_fake_desc)
test_data['pred_fake_desc'] = np.where((test_data.pred_fake_desc == '1'),1,test_data.pred_fake_desc)

In [32]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_desc'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.95      0.94      0.95      1428
           1       0.60      0.65      0.62       184

    accuracy                           0.91      1612
   macro avg       0.78      0.80      0.79      1612
weighted avg       0.91      0.91      0.91      1612



In [33]:
test_data['pred_fake_char']= predict_results3
test_data['pred_fake_char'] = np.where((test_data.pred_fake_char == '0'),0,test_data.pred_fake_char)
test_data['pred_fake_char'] = np.where((test_data.pred_fake_char == '1'),1,test_data.pred_fake_char)

In [34]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_char'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.97      0.96      0.96      1428
           1       0.73      0.73      0.73       184

    accuracy                           0.94      1612
   macro avg       0.85      0.85      0.85      1612
weighted avg       0.94      0.94      0.94      1612



In [35]:
test_data['pred_fake_word']= predict_results4
test_data['pred_fake_word'] = np.where((test_data.pred_fake_word == '0'),0,test_data.pred_fake_word)
test_data['pred_fake_word'] = np.where((test_data.pred_fake_word == '1'),1,test_data.pred_fake_word)

In [36]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_word'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1428
           1       0.88      0.66      0.76       184

    accuracy                           0.95      1612
   macro avg       0.92      0.83      0.86      1612
weighted avg       0.95      0.95      0.95      1612



In [37]:
test_data['pred_fake_text']= predict_results5
test_data['pred_fake_text'] = np.where((test_data.pred_fake_text == '0'),0,test_data.pred_fake_text)
test_data['pred_fake_text'] = np.where((test_data.pred_fake_text == '1'),1,test_data.pred_fake_text)

In [38]:
print(type(test_data['Fake']))
test_data['Fake'].head()

<class 'pandas.core.series.Series'>


0    0
1    0
2    0
3    0
4    0
Name: Fake, dtype: int64

In [40]:
print(type(test_data['pred_fake_text']))
test_data['pred_fake_text'].head()

<class 'pandas.core.series.Series'>


0    0
1    0
2    0
3    0
4    0
Name: pred_fake_text, dtype: int64

In [43]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_text'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1428
           1       0.87      0.71      0.78       184

    accuracy                           0.95      1612
   macro avg       0.92      0.85      0.88      1612
weighted avg       0.95      0.95      0.95      1612



In [44]:
test_data['pred_fake_URL']= predict_results
test_data['pred_fake_URL'] = np.where((test_data.pred_fake_URL == '0'),0,test_data.pred_fake_URL)
test_data['pred_fake_URL'] = np.where((test_data.pred_fake_URL == '1'),1,test_data.pred_fake_URL)

In [45]:
print(type(test_data['Fake']))
test_data['Fake'].head()

<class 'pandas.core.series.Series'>


0    0
1    0
2    0
3    0
4    0
Name: Fake, dtype: int64

In [46]:
print(type(test_data['pred_fake_URL']))
test_data['pred_fake_URL'].head()

<class 'pandas.core.series.Series'>


0    0
1    0
2    0
3    0
4    0
Name: pred_fake_URL, dtype: int64

In [47]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_URL'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1428
           1       0.95      0.68      0.79       184

    accuracy                           0.96      1612
   macro avg       0.95      0.84      0.89      1612
weighted avg       0.96      0.96      0.96      1612



In [48]:
np.savetxt('All_URL_title.txt', predictions1)
np.savetxt('All_URL_desc.txt', predictions2)
np.savetxt('All_URL_char.txt', predictions3)
np.savetxt('All_URL_word.txt', predictions4)
np.savetxt('All_text.txt', predictions5)
np.savetxt('All_URL.txt', predictions)

In [49]:
final_model.save('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\All_URL') 
#json_string1 = tokenizer.to_json()

INFO:tensorflow:Assets written to: C:\Users\Jan Catherine\Documents\CMSC Notes\CMSC 190 Part 2\Codes\CNN\All_URL\assets


INFO:tensorflow:Assets written to: C:\Users\Jan Catherine\Documents\CMSC Notes\CMSC 190 Part 2\Codes\CNN\All_URL\assets


In [50]:
test_data.to_csv('Test_Results.csv')

In [ ]:
#import json
#with open('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\All_URL\\All_URL.json', 'w') as outfile:
#    json.dump(json_string, outfile)