In [1]:
%%script C:\Users\Jan Catherine\AppData\Local\Programs\Python\Python38\python.exe
import sys
print(sys.version)

3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]


In [2]:
pwd

'C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN'

In [3]:
import os
os.chdir('../../Data_Collection_03/02_Preprocessing/05_CNN')

In [4]:
import matplotlib.pyplot as plt
import os
import re
import shutil
import string
import tensorflow as tf
from tensorflow.keras import regularizers

from tensorflow.keras import layers
from tensorflow.keras import losses

from collections import Counter

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from tensorflow.keras import preprocessing
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.losses import BinaryCrossentropy


from sklearn.model_selection import KFold

#import pydot

In [5]:
testdata = pd.read_csv('02_All_Test.csv', encoding='latin-1')

test_data = testdata

test_data.dropna(axis = 0, how ='any',inplace=True) 

In [6]:
new_model1 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\Title')
new_model1.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4_1 (Embedding)   (None, 90, 64)            750016    
                                                                 
 conv1d_4_1 (Conv1D)         (None, 88, 128)           24704     
                                                                 
 global_max_pooling1d_4_1 (  (None, 128)               0         
 GlobalMaxPooling1D)                                             
                                                                 
 dropout_4_1 (Dropout)       (None, 128)               0         
                                                                 
 dense_4_1 (Dense)           (None, 2)                 258       
                                                                 
Total params: 774978 (2.96 MB)
Trainable params: 774978 (2.96 MB)
Non-trainable params: 0 (0.00 Byte)
__________________

In [7]:
import json
with open('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\Title\\Title.json') as json_file1:
    json_string1 = json.loads(json_file1.read())
tokenizer1 = tf.keras.preprocessing.text.tokenizer_from_json(json_string1)

In [8]:
new_model2 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\Desc')
new_model2.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 50, 64)            1280064   
                                                                 
 conv1d_4 (Conv1D)           (None, 48, 128)           24704     
                                                                 
 global_max_pooling1d_4 (Gl  (None, 128)               0         
 obalMaxPooling1D)                                               
                                                                 
 dropout_4 (Dropout)         (None, 128)               0         
                                                                 
 dense_4 (Dense)             (None, 2)                 258       
                                                                 
Total params: 1305026 (4.98 MB)
Trainable params: 1305026 (4.98 MB)
Non-trainable params: 0 (0.00 Byte)
________________

In [9]:
import json
with open('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\Desc\\Desc.json') as json_file2:
    json_string2 = json.loads(json_file2.read())
tokenizer2 = tf.keras.preprocessing.text.tokenizer_from_json(json_string2)

In [10]:
new_model3 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\URLchar')
new_model3.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 260, 64)           750016    
                                                                 
 conv1d_4 (Conv1D)           (None, 258, 128)          24704     
                                                                 
 global_max_pooling1d_4 (Gl  (None, 128)               0         
 obalMaxPooling1D)                                               
                                                                 
 dropout_4 (Dropout)         (None, 128)               0         
                                                                 
 dense_4 (Dense)             (None, 2)                 258       
                                                                 
Total params: 774978 (2.96 MB)
Trainable params: 774978 (2.96 MB)
Non-trainable params: 0 (0.00 Byte)
__________________

In [11]:
with open('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\URLchar\\URLchar.json') as json_file3:
    json_string3 = json.load(json_file3)
tokenizer3 = tf.keras.preprocessing.text.tokenizer_from_json(json_string3)

In [12]:
new_model4 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\URLword')
new_model4.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4_word (Embeddin  (None, 40, 64)            750016    
 g)                                                              
                                                                 
 conv1d_4_word (Conv1D)      (None, 38, 128)           24704     
                                                                 
 global_max_pooling1d_4_wor  (None, 128)               0         
 d (GlobalMaxPooling1D)                                          
                                                                 
 dropout_4_word (Dropout)    (None, 128)               0         
                                                                 
 dense_4_word (Dense)        (None, 2)                 258       
                                                                 
Total params: 774978 (2.96 MB)
Trainable params: 77497

In [13]:
with open('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\URLword\\URLword.json') as json_file4:
    json_string4 = json.load(json_file4)
tokenizer4 = tf.keras.preprocessing.text.tokenizer_from_json(json_string4)

In [14]:
new_model5 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\All_URL')
new_model5.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 input_2 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 input_3 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 input_4 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                              

In [15]:
new_model6 = tf.keras.models.load_model('C:\\Users\\Jan Catherine\\Documents\\CMSC Notes\\CMSC 190 Part 2\\Codes\\CNN\\All_No_URL')
new_model6.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 input_2 (InputLayer)        [(None, 2)]                  0         []                            
                                                                                                  
 average (Average)           (None, 2)                    0         ['input_1[0][0]',             
                                                                     'input_2[0][0]']             
                                                                                                  
Total params: 0 (0.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 0 (0.00 Byte

In [16]:
x_test1  = np.array( tokenizer1.texts_to_sequences(test_data['Title'].tolist()) )
x_test1 = pad_sequences(x_test1, padding='post', maxlen=90)


C:\Users\Jan Catherine\AppData\Local\Temp\ipykernel_13728\3328888694.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test1  = np.array( tokenizer1.texts_to_sequences(test_data['Title'].tolist()) )


In [17]:
x_test2  = np.array( tokenizer2.texts_to_sequences(test_data['Description'].tolist()) )
x_test2 = pad_sequences(x_test2, padding='post', maxlen=50)


C:\Users\Jan Catherine\AppData\Local\Temp\ipykernel_13728\4054164706.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test2  = np.array( tokenizer2.texts_to_sequences(test_data['Description'].tolist()) )


In [18]:
x_test3  = np.array( tokenizer3.texts_to_sequences(test_data['URL'].tolist()) )
x_test3 = pad_sequences(x_test3, padding='post', maxlen=260)


C:\Users\Jan Catherine\AppData\Local\Temp\ipykernel_13728\1739419470.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test3  = np.array( tokenizer3.texts_to_sequences(test_data['URL'].tolist()) )


In [19]:
x_test4  = np.array( tokenizer4.texts_to_sequences(test_data['URL'].tolist()) )
x_test4 = pad_sequences(x_test4, padding='post', maxlen=40)


C:\Users\Jan Catherine\AppData\Local\Temp\ipykernel_13728\2258211110.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test4  = np.array( tokenizer4.texts_to_sequences(test_data['URL'].tolist()) )


In [20]:
print("Generate predictions for all samples")
predictions1 = new_model1.predict(x_test1)
print(predictions1)
predict_results1 = predictions1.argmax(axis=1)

Generate predictions for all samples
27/27 [==============================] - 0s 4ms/step
[[9.9958450e-01 4.1550127e-04]
 [9.9982953e-01 1.7049181e-04]
 [9.8916990e-01 1.0830079e-02]
 ...
 [9.7679418e-01 2.3205804e-02]
 [9.8604935e-01 1.3950633e-02]
 [9.9202150e-01 7.9784933e-03]]


In [21]:
print("Generate predictions for all samples")
predictions2 = new_model2.predict(x_test2)
print(predictions2)
predict_results2 = predictions2.argmax(axis=1)

Generate predictions for all samples
27/27 [==============================] - 0s 3ms/step
[[0.94111526 0.05888475]
 [0.99540746 0.00459254]
 [0.97648996 0.02351002]
 ...
 [0.97934484 0.02065513]
 [0.9979575  0.00204247]
 [0.9808166  0.01918339]]


In [22]:
print("Generate predictions for all samples")
predictions3 = new_model3.predict(x_test3)
print(predictions3)
predict_results3 = predictions3.argmax(axis=1)

Generate predictions for all samples
27/27 [==============================] - 0s 6ms/step
[[0.79100466 0.20899567]
 [0.87620866 0.12379212]
 [0.8144461  0.18555513]
 ...
 [0.4058216  0.59417593]
 [0.50849885 0.4914994 ]
 [0.98134935 0.01865079]]


In [23]:
print("Generate predictions for all samples")
predictions4 = new_model4.predict(x_test4)
print(predictions4)
predict_results4 = predictions4.argmax(axis=1)

Generate predictions for all samples
27/27 [==============================] - 0s 2ms/step
[[0.9915817  0.00841829]
 [0.99103314 0.0089669 ]
 [0.9577367  0.04226334]
 ...
 [0.96305877 0.03694125]
 [0.9608643  0.0391357 ]
 [0.9938769  0.00612312]]


In [24]:
print("Generate predictions for all samples")
predictions5 = new_model5.predict([predictions1, predictions2, predictions3, predictions4 ])
print(predictions5)
predict_results5 = predictions5.argmax(axis=1)

Generate predictions for all samples
27/27 [==============================] - 0s 1ms/step
[[0.93082154 0.06917855]
 [0.9656197  0.03438051]
 [0.9344607  0.06553964]
 ...
 [0.83125484 0.16874452]
 [0.8633425  0.13665704]
 [0.9870161  0.01298395]]


In [25]:
print("Generate predictions for all samples")
predictions6 = new_model6.predict([predictions1, predictions2])
print(predictions6)
predict_results6 = predictions6.argmax(axis=1)

Generate predictions for all samples
27/27 [==============================] - 0s 1ms/step
[[0.9703499  0.02965013]
 [0.9976185  0.00238151]
 [0.9828299  0.01717005]
 ...
 [0.97806954 0.02193047]
 [0.99200344 0.00799655]
 [0.9864191  0.01358094]]


In [26]:
test_data['pred_fake_title']= predict_results1
test_data['pred_fake_title'] = np.where((test_data.pred_fake_title == '0'),0,test_data.pred_fake_title)
test_data['pred_fake_title'] = np.where((test_data.pred_fake_title == '1'),1,test_data.pred_fake_title)

In [27]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_title'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.85      0.98      0.91       699
           1       0.68      0.19      0.29       151

    accuracy                           0.84       850
   macro avg       0.77      0.58      0.60       850
weighted avg       0.82      0.84      0.80       850



In [28]:
test_data['pred_fake_desc']= predict_results2
test_data['pred_fake_desc'] = np.where((test_data.pred_fake_desc == '0'),0,test_data.pred_fake_desc)
test_data['pred_fake_desc'] = np.where((test_data.pred_fake_desc == '1'),1,test_data.pred_fake_desc)

In [29]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_desc'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.84      0.96      0.90       699
           1       0.47      0.19      0.27       151

    accuracy                           0.82       850
   macro avg       0.66      0.57      0.58       850
weighted avg       0.78      0.82      0.78       850



In [30]:
test_data['pred_fake_char']= predict_results3
test_data['pred_fake_char'] = np.where((test_data.pred_fake_char == '0'),0,test_data.pred_fake_char)
test_data['pred_fake_char'] = np.where((test_data.pred_fake_char == '1'),1,test_data.pred_fake_char)

In [31]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_char'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.86      0.90      0.88       699
           1       0.40      0.31      0.35       151

    accuracy                           0.80       850
   macro avg       0.63      0.61      0.61       850
weighted avg       0.78      0.80      0.78       850



In [32]:
test_data['pred_fake_word']= predict_results4
test_data['pred_fake_word'] = np.where((test_data.pred_fake_word == '0'),0,test_data.pred_fake_word)
test_data['pred_fake_word'] = np.where((test_data.pred_fake_word == '1'),1,test_data.pred_fake_word)

In [33]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_word'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.86      0.98      0.91       699
           1       0.73      0.24      0.36       151

    accuracy                           0.85       850
   macro avg       0.80      0.61      0.64       850
weighted avg       0.83      0.85      0.82       850



In [34]:
test_data['pred_fake_text']= predict_results6
test_data['pred_fake_text'] = np.where((test_data.pred_fake_text == '0'),0,test_data.pred_fake_text)
test_data['pred_fake_text'] = np.where((test_data.pred_fake_text == '1'),1,test_data.pred_fake_text)

In [35]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_text'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.84      1.00      0.91       699
           1       0.82      0.09      0.17       151

    accuracy                           0.84       850
   macro avg       0.83      0.54      0.54       850
weighted avg       0.83      0.84      0.78       850



In [36]:
test_data['pred_fake_URL']= predict_results5
test_data['pred_fake_URL'] = np.where((test_data.pred_fake_URL == '0'),0,test_data.pred_fake_URL)
test_data['pred_fake_URL'] = np.where((test_data.pred_fake_URL == '1'),1,test_data.pred_fake_URL)

In [37]:
print(type(test_data['Fake']))
test_data['Fake'].head()

<class 'pandas.core.series.Series'>


0    0
1    0
2    0
3    0
4    1
Name: Fake, dtype: int64

In [38]:
print(type(test_data['pred_fake_URL']))
test_data['pred_fake_URL'].head()

<class 'pandas.core.series.Series'>


0    0
1    0
2    0
3    0
4    0
Name: pred_fake_URL, dtype: int64

In [39]:
labels = [0, 1]
    
print(classification_report(test_data['Fake'].tolist(),test_data['pred_fake_URL'].tolist(),labels=labels))

              precision    recall  f1-score   support

           0       0.84      1.00      0.91       699
           1       0.95      0.13      0.22       151

    accuracy                           0.84       850
   macro avg       0.90      0.56      0.57       850
weighted avg       0.86      0.84      0.79       850



In [40]:
np.savetxt('All_URL_title_02.txt', predictions1)
np.savetxt('All_URL_desc_02.txt', predictions2)
np.savetxt('All_URL_char_02.txt', predictions3)
np.savetxt('All_URL_word_02.txt', predictions4)
np.savetxt('All_text_02.txt', predictions5)
np.savetxt('All_URL_02.txt', predictions6)

In [41]:
test_data.to_csv('NewTest_Results.csv')